apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-test
  namespace: argocd-test
  labels:
    app: gitops-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-test
  template:
    metadata:
      labels:
        app: gitops-test
    spec:
      containers:
      - name: gitops-test
        image: ghcr.io/migorithm/gitops-test:c6f2c891
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
      imagePullSecrets:
      - name: gitops-test