apiVersion: v1
kind: Service
metadata:
  name: gitops-test
  namespace: argocd-test
spec:
  type: NodePort
  selector:
    app: gitops-test 
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
